export const designTokens = {
  fontFamily: {
    base: '"Noto Sans KR", sans-serif',
  },
  color: {
    primary: "rgba(72, 128, 238, 1)",
    red: "rgba(232, 65, 24, 1)",
    gray: "rgba(218, 218, 218, 1)",
    gray50: "rgba(218, 218, 218, 0.5)",
    gray60: "rgba(218, 218, 218, 0.6)",
    gray80: "rgba(218, 218, 218, 0.8)",
    lightgray: "rgba(242, 244, 246, 1)",
    white: "rgba(255, 255, 255, 1)",
    whiteOverlay: "rgba(255, 255, 255, 0.4)",
    black: "rgba(34, 34, 34, 1)",
    border: "rgba(210, 214, 218, 1)",
    borderSoft: "rgba(218, 218, 218, 0.8)",
    redSoft: "rgba(232, 65, 24, 0.4)",
  },
  textColor: {
    primary: "rgba(53, 60, 73, 1)",
    secondary: "rgba(109, 117, 130, 1)",
    subtitle: "rgba(141, 148, 160, 1)",
  },
  typography: {
    title1: { size: "24px", lineHeight: "24px", weight: 700 },
    title2: { size: "22px", lineHeight: "24px", weight: 700 },
    title3: { size: "18px", lineHeight: "18px", weight: 700 },
    body1: { size: "20px", lineHeight: "20px", weight: 500 },
    body2: { size: "14px", lineHeight: "14px", weight: 500 },
    body2Bold: { size: "14px", lineHeight: "14px", weight: 700 },
    caption: { size: "16px", lineHeight: "16px", weight: 500 },
    small: { size: "10px", lineHeight: "10px", weight: 500 },
    tab: { size: "20px", lineHeight: "20px", weight: 500 },
  },
  radius: {
    xs: "10px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    xxl: "32px",
  },
  shadow: {
    card: "0 16px 50px rgba(53, 60, 73, 0.08)",
    floating: "0 16px 28px rgba(53, 60, 73, 0.14)",
    dropdown: "0 20px 40px rgba(53, 60, 73, 0.16)",
    header: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
  },
} as const;

export const cssVariables = {
  "--font-family-base": designTokens.fontFamily.base,
  "--color-primary": designTokens.color.primary,
  "--color-red": designTokens.color.red,
  "--color-gray": designTokens.color.gray,
  "--color-gray-50": designTokens.color.gray50,
  "--color-gray-60": designTokens.color.gray60,
  "--color-gray-80": designTokens.color.gray80,
  "--color-lightgray": designTokens.color.lightgray,
  "--color-white": designTokens.color.white,
  "--color-white-overlay": designTokens.color.whiteOverlay,
  "--color-black": designTokens.color.black,
  "--color-border": designTokens.color.border,
  "--color-border-soft": designTokens.color.borderSoft,
  "--color-red-soft": designTokens.color.redSoft,
  "--text-color-primary": designTokens.textColor.primary,
  "--text-color-secondary": designTokens.textColor.secondary,
  "--text-color-subtitle": designTokens.textColor.subtitle,
  "--text-title-1-size": designTokens.typography.title1.size,
  "--text-title-1-line-height": designTokens.typography.title1.lineHeight,
  "--text-title-1-weight": String(designTokens.typography.title1.weight),
  "--text-title-2-size": designTokens.typography.title2.size,
  "--text-title-2-line-height": designTokens.typography.title2.lineHeight,
  "--text-title-2-weight": String(designTokens.typography.title2.weight),
  "--text-title-3-size": designTokens.typography.title3.size,
  "--text-title-3-line-height": designTokens.typography.title3.lineHeight,
  "--text-title-3-weight": String(designTokens.typography.title3.weight),
  "--text-body-1-size": designTokens.typography.body1.size,
  "--text-body-1-line-height": designTokens.typography.body1.lineHeight,
  "--text-body-1-weight": String(designTokens.typography.body1.weight),
  "--text-body-2-size": designTokens.typography.body2.size,
  "--text-body-2-line-height": designTokens.typography.body2.lineHeight,
  "--text-body-2-weight": String(designTokens.typography.body2.weight),
  "--text-body-2-bold-size": designTokens.typography.body2Bold.size,
  "--text-body-2-bold-line-height":
    designTokens.typography.body2Bold.lineHeight,
  "--text-body-2-bold-weight": String(designTokens.typography.body2Bold.weight),
  "--text-caption-size": designTokens.typography.caption.size,
  "--text-caption-line-height": designTokens.typography.caption.lineHeight,
  "--text-caption-weight": String(designTokens.typography.caption.weight),
  "--text-small-size": designTokens.typography.small.size,
  "--text-small-line-height": designTokens.typography.small.lineHeight,
  "--text-small-weight": String(designTokens.typography.small.weight),
  "--radius-xs": designTokens.radius.xs,
  "--radius-sm": designTokens.radius.sm,
  "--radius-md": designTokens.radius.md,
  "--radius-lg": designTokens.radius.lg,
  "--radius-xl": designTokens.radius.xl,
  "--radius-xxl": designTokens.radius.xxl,
  "--shadow-card": designTokens.shadow.card,
  "--shadow-floating": designTokens.shadow.floating,
  "--shadow-dropdown": designTokens.shadow.dropdown,
  "--shadow-header": designTokens.shadow.header,
} as const;

export const theme = {
  fontFamily: {
    base: "var(--font-family-base)",
  },
  color: {
    primary: "var(--color-primary)",
    red: "var(--color-red)",
    gray: "var(--color-gray)",
    gray50: "var(--color-gray-50)",
    gray60: "var(--color-gray-60)",
    gray80: "var(--color-gray-80)",
    lightgray: "var(--color-lightgray)",
    white: "var(--color-white)",
    whiteOverlay: "var(--color-white-overlay)",
    black: "var(--color-black)",
    border: "var(--color-border)",
    borderSoft: "var(--color-border-soft)",
    redSoft: "var(--color-red-soft)",
  },
  textColor: {
    primary: "var(--text-color-primary)",
    secondary: "var(--text-color-secondary)",
    subtitle: "var(--text-color-subtitle)",
  },
  typography: {
    title1: {
      size: "var(--text-title-1-size)",
      lineHeight: "var(--text-title-1-line-height)",
      weight: "var(--text-title-1-weight)",
    },
    title2: {
      size: "var(--text-title-2-size)",
      lineHeight: "var(--text-title-2-line-height)",
      weight: "var(--text-title-2-weight)",
    },
    title3: {
      size: "var(--text-title-3-size)",
      lineHeight: "var(--text-title-3-line-height)",
      weight: "var(--text-title-3-weight)",
    },
    body1: {
      size: "var(--text-body-1-size)",
      lineHeight: "var(--text-body-1-line-height)",
      weight: "var(--text-body-1-weight)",
    },
    body2: {
      size: "var(--text-body-2-size)",
      lineHeight: "var(--text-body-2-line-height)",
      weight: "var(--text-body-2-weight)",
    },
    body2Bold: {
      size: "var(--text-body-2-bold-size)",
      lineHeight: "var(--text-body-2-bold-line-height)",
      weight: "var(--text-body-2-bold-weight)",
    },
    caption: {
      size: "var(--text-caption-size)",
      lineHeight: "var(--text-caption-line-height)",
      weight: "var(--text-caption-weight)",
    },
    small: {
      size: "var(--text-small-size)",
      lineHeight: "var(--text-small-line-height)",
      weight: "var(--text-small-weight)",
    },
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    xxl: "var(--radius-xxl)",
  },
  shadow: {
    card: "var(--shadow-card)",
    floating: "var(--shadow-floating)",
    dropdown: "var(--shadow-dropdown)",
    header: "var(--shadow-header)",
  },
} as const;

export type AppTheme = typeof theme;
